version: '3'

services:
    web:
      build: ./nginx
      container_name: learn_nginx
      volumes:
        - ./www/php:/usr/share/nginx/html
      restart: unless-stopped
      ports:
        - "80:80"
      environment:
              - NGINX_HOST=localhost
              - NGINX_PORT=80
      networks:
        - default
    learn_mysql:
      build: ./mysql
      container_name: learn_mysql
      environment:
        MYSQL_ROOT_PASSWORD: masterkey
        MYSQL_DATABASE: learn_mysql
      ports:
        - "3282:3306"
      volumes:
        - learn-db:/var/lib/mysql
      networks:
        - default
#    flask:
#       build: ./www/flask
#       container_name: flask
#       ports:
#         - "8000:8000"
#       volumes:
#         - ./www/flask:/app
#       networks:
#         - default
#    nodejs:
#        build: ./www/node
#        container_name: nodejs
#        restart: unless-stopped
#        ports:
#          - "3000:3000"
#        volumes:
#          - ./www/node:/usr/src/app
#        working_dir: /usr/src/app

networks:
  default:
    driver: bridge
volumes:
  learn-db:
